version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.4.1
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@1.0.0

workflows:
  multiple-ghcs:
    jobs:
      - haskell/build:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4

      - haskell/build:
          name: GHC 8.6.3
          executor: haskell/ghc-8_6_3

      - haskell/build:
          name: GHC 7.10.3
          executor: haskell/ghc-7_10_3

      - github/release-cabal:
          name: GitHub Release
          checkout: true
          requires:
            - GHC 8.4.4
            - GHC 8.6.3
            - GHC 7.10.3
          filters:
            branches:
              only: master

      - hackage/upload:
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
          filters:
            branches:
              only: master
